### ISSUE TITLE
property with null value in source object not overwriting to same property in target object

### ISSUE THREAD

**Issue by topgun743** [sindresorhus/deep-assign#23]
Hi Dev,
Following is not working correct:

`var deepAssign = require("deep-assign");`
`deepAssign({}, {Lat: null, Lon: null}, {Lat: null, Lon: 2})`

output is: 
`{Lon: 2}`

It must be:
`{Lat: null, Lon 2}`

Due to this weird issue, my form validation is failing as Lat property is totally missing from output. 
If I use Object.assign, it works correctly. 
Can you plz guide me what is wrong?

**Comment by schnittstabil** [comment]
Unfortunately, this's on purpose. From [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Primitives_will_be_wrapped_to_objects):

> … null and undefined will be ignored.

More precisely, this is due to the [ECMAScript® 2015 Language Specification; 19.1.2.1 `Object.assign`](http://www.ecma-international.org/ecma-262/6.0/#sec-object.assign):
> 5.a If _nextSource_ is `undefined` or `null`, let _keys_ be an empty List.

As `deep-assign` is _Recursive `Object.assign()`_, the following happens:

```js
deepAssign({}, {Lat: null, …}, {Lat: null, …})

// should be similar to
{Lat: deepAssign(<?>, null, null), …}

// which have to be the same as 
{Lat: Object.assign(<?>, null, null), …}
```

The `<?>` and the exact recursive semantic is debatable in this case. `deep-assign` ignores the `<?>` at the moment – to be at least a bit useful. But in all possible interpretations, the (additional) `null` values must be ignored because of the spec.

Hence, I believe `deep-assign` does not match your requirements. There are many merge tools doing this in a different way. Some examples:
- [_.merge](https://www.npmjs.com/package/lodash.merge) (2208 loc)
- [merge-options](https://github.com/schnittstabil/merge-options) (153 loc) – disclaimer: I'm the author of it
- [and many more at npm…](https://www.npmjs.com/search?q=merge%20&page=1&ranking=optimal)

**Comment by topgun743** [comment]
This is strange behavior suggested by ECMA. Null may b a valid and intended value from source. How come not accept it? Also deepAssign must provide an option to even allow such kind of merging.

**Comment by schnittstabil** [comment]
It would be nice to provide options somehow, but the signature is:
> `deepAssign(target, source, [source, ...])`

If you have an idea, which does not conflict with the semantics of `Object.assign`, then please let us know.

Btw, we _must_ not provide an option – we are free to do; and we are not ECMA of course :wink:. `deep-assign` is fully dedicated being _Recursive `Object.assign()`_; therefore we can also create a new project with a different semantic – like, I did with [merge-options](https://github.com/schnittstabil/merge-options).

@topgun743 Anyway, does neither `_.merge` nor `merge-options` provide you the semantic you need?

**Comment by topgun743** [comment]
Looks like I have to turn towards your suggestion. Yes, `merge-options` looks nice. Will use it now off course. Thanks for suggesting. Great !

**Comment by topgun743** [comment]
BTW, you can allow a last object as an option config sort of to `deepAssign` whose first property can be like 

`{allowNulls: true,   . . . . . . other options}`

This way it would be assumed that even null values from source should be forced onto the target. I think it should work.

**Comment by schnittstabil** [comment]
Sadly, because of the `Object.assign` signature/semantics, these options must be also assigned to the result object, which would be undesirable in my opinion.
