### ISSUE TITLE
Source object get manipulated

### ISSUE THREAD

**Issue by myst729** [sindresorhus/deep-assign#24]
Node version: 7.3.0

```js
var deepAssign = require('deep-assign')
var o1 = {a: {b: 2}, d: {e: 5}}
var o2 = {a: {c: 3}, d: {f: 6}}
var o3 = deepAssign({}, o1, o2)
console.log(o3) // { a: { b: 2, c: 3 }, d: { e: 5, f: 6 } }
console.log(o1) // { a: { b: 2, c: 3 }, d: { e: 5, f: 6 } }
```

<img src="https://cloud.githubusercontent.com/assets/519733/21690786/c8d0b972-d3b0-11e6-9139-49c0dea96299.png" width="302" height="198">

Source object should be kept intact, like `Object.assign`.

**Comment by schnittstabil** [comment]
**tl;tr** I'd love to fulfill that invariant, but as far as I can see it is not possible.

For example:
```js
const source1 = {noop: () => {}};
const source2 = {noop: {unicorns: 42}};

const result = deepAssign({}, source1, source2);

result.noop.unicorns; //=> 42
```

As we cannot _clone_ the `source1.noop` function, `source1.noop.unicorns` will be unavoidably modified; and there exists many similar examples of that kind.

> Source object should be kept intact, like `Object.assign`.

Unfortunately, that does not really matter, because:
1. `Object.assign` is not recursive.
2. `Object.assign` modifies some arguments (the first one) and does not modify other arguments (the rest) – hence, deducing that `deepAssign` _must/should_ not modify its non-first arguments is not per se possible.

**Comment by myst729** [comment]
Well, I've gone through the source code. The behavior varies on different types indeed.

Also I tried some other use cases and found in some cases arrays become non-array objects.

```js
oa = {a: [2]}
r1 = deepAssign({}, oa)
console.log(oa) // { a: [ 2 ] }
console.log(r1) // { a: [ 2 ] }
console.log(Array.isArray(r1.a)) // true

pn = {a: 1}
pa = {a: [2]}
r2 = deepAssign({}, pn, pa)
console.log(pn) // { a: 1 }
console.log(pa) // { a: [ 2 ] }
console.log(r2) // { a: { [Number: 1] '0': 2 } }
console.log(Array.isArray(r2.a)) // false
```

**Comment by schnittstabil** [comment]
@myst729 As far as I can see, your new example is unrelated to this issue and your first example, isn't it?

`Object.assign` is doing the same, see the [ECMAScript® 2015 Language Specification](http://www.ecma-international.org/ecma-262/6.0/#sec-object.assign) for details. For example:
```js
const r = Object.assign(1, [2]);
console.log(r);  // => { [Number: 1] '0': 2 }
Array.isArray(r) // => false
```
