### ISSUE TITLE
it mutates *some* of the sources

### ISSUE THREAD

**Issue by educastellano** [sindresorhus/deep-assign#25]
Is this the correct behaviour...?

```js
let a = {x:{}}
let b = {x: {y: 1}}
let c = {x: {y: 2}}
deepAssign({}, a, b, c)
// { x: { y: 2 } }

console.log(a)
// { x: { y: 2 } }  <-- mutated!
console.log(b)
// { x: { y: 1 } }
console.log(c)
// { x: { y: 2 } }
```

It's quite a dangerous thing to mutate the sources, but if that's what this lib wants to be, shouldn't it mutate `b` too?

**Comment by schnittstabil** [comment]
`deep-assign` suffers from this behavior for some time – unfortunately, the problem is that, simply _recursive Object.assign()_ does not work as hoped.

The problem is that functions etc. are objects too, and we cannot _clone_ them. Using your example:

```js
const a = {x: () => 42}
const b = {x: {y: 1}}
const result = deepAssign({}, a, b);

console.log(result.x()) // should print 42
console.log(result.x.y) // should print 1
```

Sorry, I'm not aware of any good solution to this, at the moment `a.x` is mutated by `deep-assign`.

If we take a look at the [Object.assign Spec](http://www.ecma-international.org/ecma-262/6.0/#sec-object.assign), then we see that `Object.assign` does not distinguish functions etc. from _plain_ objects; therefore there is no (sufficient) reason for `deep-assign` to do so.

There are many merge tools doing this in a different way, for example:
- [`_.merge`](https://lodash.com/docs/#merge)
- [`merge-options`](https://github.com/schnittstabil/merge-options) – does not mutate anything (disclaimer: I'm the author of it)

**Comment by schnittstabil** [comment]
> shouldn't it mutate `b` too?

Well, I do not know. Did you expect that?

**Comment by educastellano** [comment]
Well no, I wasn't expecting that 😅 Just some coherence, either all or none mutated.

Thanks for the answer @schnittstabil ! :) 
I found [assign-deep](https://github.com/jonschlinkert/assign-deep) which seems to work well 👍

**Comment by schnittstabil** [comment]
@educastellano Thanks for the link, I was not aware of that project. The crucial difference of `deep-assign` and `assign-deep` can be seen at [assign-deep/index.js line 60](https://github.com/jonschlinkert/assign-deep/blob/99f44f8f69f83f5d3c64f0c8b892d5e17e638c9e/index.js#L59-L61) using [`kind-of`](https://github.com/jonschlinkert/kind-of):

```js
var typeOf = require('kind-of');
// …
function isObject(obj) {
  return typeOf(obj) === 'object' || typeOf(obj) === 'function';
}
```

The problem I see here is:
The distinction between _objects_ and _non-objects_ is neither based on the behavior of [Object.assign](http://www.ecma-international.org/ecma-262/6.0/#sec-object.assign) nor on what an object in JavaScript _is_. Therefore it should be is easy to find some unexpected behavior of `assign-deep` too.

I do not want to go into details of `assign-deep`, but as far as I can see, it probably would not meet your requirements – `assign-deep` also mutates sources:

```js
const src1 = {
	b: new Buffer (1),
	p: Promise.resolve(42)
};

const src2 = {
	b: {c: 666},
	p: {q: 666},
};

assignDeep({}, src1, src2);

console.log(src1.b.c) // => 666

// but:
console.log(src1.p.q) // => undefined
```

**Comment by educastellano** [comment]
Good to know... It doesn't seem very appropiate to use [kind-of](https://github.com/jonschlinkert/kind-of) for that library. `isObject()` should say if the value is really an `object` (not `buffer` or `boolean` in case of `new Boolean()`,...) . /cc @jonschlinkert
